#!/bin/bash
cp /home/singheart/project/database/cmu15445-2020/src/include/buffer/lru_replacer.h ./
cp /home/singheart/project/database/cmu15445-2020/src/buffer/lru_replacer.cpp ./
cp /home/singheart/project/database/cmu15445-2020/src/include/buffer/buffer_pool_manager.h ./
cp /home/singheart/project/database/cmu15445-2020/src/buffer/buffer_pool_manager.cpp ./
cp /home/singheart/project/database/cmu15445-2020/src/include/storage/page/b_plus_tree_page.h ./
cp /home/singheart/project/database/cmu15445-2020/src/storage/page/b_plus_tree_page.cpp ./
cp /home/singheart/project/database/cmu15445-2020/src/include/storage/page/b_plus_tree_internal_page.h ./
cp /home/singheart/project/database/cmu15445-2020/src/storage/page/b_plus_tree_internal_page.cpp ./
cp /home/singheart/project/database/cmu15445-2020/src/include/storage/page/b_plus_tree_leaf_page.h ./
cp /home/singheart/project/database/cmu15445-2020/src/storage/page/b_plus_tree_leaf_page.cpp ./
cp /home/singheart/project/database/cmu15445-2020/src/include/storage/index/b_plus_tree.h ./
cp /home/singheart/project/database/cmu15445-2020/src/storage/index/b_plus_tree.cpp ./
cp /home/singheart/project/database/cmu15445-2020/src/include/storage/index/index_iterator.h ./
cp /home/singheart/project/database/cmu15445-2020/src/storage/index/index_iterator.cpp ./
cp /home/singheart/project/database/cmu15445-2020/src/include/catalog/catalog.h ./
cp /home/singheart/project/database/cmu15445-2020/src/include/execution/execution_engine.h ./
cp /home/singheart/project/database/cmu15445-2020/src/include/execution/executor_factory.h ./
cp /home/singheart/project/database/cmu15445-2020/src/include/execution/executors/seq_scan_executor.h ./
cp /home/singheart/project/database/cmu15445-2020/src/include/execution/executors/index_scan_executor.h ./
cp /home/singheart/project/database/cmu15445-2020/src/include/execution/executors/insert_executor.h ./
cp /home/singheart/project/database/cmu15445-2020/src/include/execution/executors/update_executor.h ./
cp /home/singheart/project/database/cmu15445-2020/src/include/execution/executors/delete_executor.h ./
cp /home/singheart/project/database/cmu15445-2020/src/include/execution/executors/nested_loop_join_executor.h ./
cp /home/singheart/project/database/cmu15445-2020/src/include/execution/executors/nested_index_join_executor.h ./
cp /home/singheart/project/database/cmu15445-2020/src/include/execution/executors/limit_executor.h ./
cp /home/singheart/project/database/cmu15445-2020/src/include/execution/executors/aggregation_executor.h ./
cp /home/singheart/project/database/cmu15445-2020/src/include/storage/index/b_plus_tree_index.h ./
cp /home/singheart/project/database/cmu15445-2020/src/include/storage/index/index.h ./
cp /home/singheart/project/database/cmu15445-2020/src/execution/executor_factory.cpp ./
cp /home/singheart/project/database/cmu15445-2020/src/execution/seq_scan_executor.cpp ./
cp /home/singheart/project/database/cmu15445-2020/src/execution/index_scan_executor.cpp ./
cp /home/singheart/project/database/cmu15445-2020/src/execution/insert_executor.cpp ./
cp /home/singheart/project/database/cmu15445-2020/src/execution/update_executor.cpp ./
cp /home/singheart/project/database/cmu15445-2020/src/execution/delete_executor.cpp ./
cp /home/singheart/project/database/cmu15445-2020/src/execution/nested_loop_join_executor.cpp ./
cp /home/singheart/project/database/cmu15445-2020/src/execution/nested_index_join_executor.cpp ./
cp /home/singheart/project/database/cmu15445-2020/src/execution/limit_executor.cpp ./
cp /home/singheart/project/database/cmu15445-2020/src/execution/aggregation_executor.cpp ./
cp /home/singheart/project/database/cmu15445-2020/src/storage/index/b_plus_tree_index.cpp ./
cp /home/singheart/project/database/cmu15445-2020/src/include/storage/page/tmp_tuple_page.h ./
cp /home/singheart/project/database/cmu15445-2020/build_support/gtest_CMakeLists.txt.in ./
